# Generated by Django 6.1.1 on 2026-09-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('fees_due', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('trimester', models.CharField(choices=[('Trimester 1', 'Trimester 1'), ('Trimester 2', 'Trimester 2'), ('Trimester 3', 'Trimester 3')], default='Trimester 1', max_length=20)),
                ('class_score', models.FloatField(default=0.0)),
                ('exam_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portal.student')),
            ],
        ),
    ]
