# Generated by Django 6.1.1 on 2026-09-18 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Al-Wasilah School Complex', max_length=255)),
                ('logo_text', models.CharField(default='Al-Wasilah Portal', max_length=100)),
                ('primary_color', models.CharField(default='#581c87', max_length=7)),
                ('secondary_color', models.CharField(default='#2e1065', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='class_score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_promoted',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='index_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='trimester',
            field=models.CharField(default='First Trimester', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='year',
            field=models.CharField(default='2026/2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='portal.studentprofile'),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PendingModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher / Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.DeleteModel(
            name='ClassLevel',
        ),
    ]
