# Generated by Django 6.1.1 on 2026-09-11 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='AL-WASILAH SCHOOL COMPLEX', max_length=200)),
                ('tagline', models.CharField(default='Excellence in Knowledge & Character', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_branding/')),
                ('primary_color', models.CharField(default='#722F37', help_text='Hex Code for Wine Theme', max_length=10)),
                ('secondary_color', models.CharField(default='#4A1F24', help_text='Darker Wine for headers/accents', max_length=10)),
                ('phone_number', models.CharField(default='+233 20 000 0000', max_length=30)),
                ('email_address', models.EmailField(default='info@alwasilah.edu.gh', max_length=254)),
                ('address', models.TextField(default='Tamale, Northern Region, Ghana')),
            ],
            options={
                'verbose_name': 'School Branding Configuration',
                'verbose_name_plural': 'School Branding Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='subjectresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.CharField(blank=True, help_text='e.g. Basic 7 Gold', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject_specialization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('current_class', models.CharField(default='Unassigned', max_length=100)),
                ('guardian_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='SubjectResult',
        ),
    ]
