# Generated by Django 6.1.1 on 2026-09-19 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_schoolbranding_remove_studentprofile_current_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='grade_letter',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='total_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='trimester',
            field=models.CharField(choices=[('Trimester 1', 'Trimester 1'), ('Trimester 2', 'Trimester 2'), ('Trimester 3', 'Trimester 3')], default='Trimester 1', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='portal.classlevel'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portal.classlevel')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='portal.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='portal.course'),
        ),
        migrations.DeleteModel(
            name='PendingModification',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
