# Generated by Django 6.1.1 on 2026-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_schoolbranding_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranding',
            name='address',
            field=models.CharField(default='Tamale, Ghana', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='contact_email',
            field=models.EmailField(default='info@alwasilah.edu.gh', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='contact_phone',
            field=models.CharField(default='+233 20 000 0000', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='index_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_picture',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20),
        ),
    ]
