# Generated by Django 6.1.1 on 2026-09-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_schoolbranding_address_schoolbranding_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranding',
            name='accent_color',
            field=models.CharField(default='#eab308', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='banner_announcement',
            field=models.CharField(blank=True, default='Welcome to the official Al-Wasilah Portal!', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='enable_top_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 Al-Wasilah School Complex. All Rights Reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='website_url',
            field=models.URLField(blank=True, default='https://alwasilah.edu.gh'),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+233 20 000 0000', max_length=20),
        ),
    ]
