# Generated by Django 6.1 on 2026-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_classschedule_attendancerecord_graderecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.RemoveField(
            model_name='graderecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='schoolbranding',
            options={},
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#800020', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='school_name',
            field=models.CharField(default='Al-Wasilah School Complex', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='secondary_color',
            field=models.CharField(default='#1A252C', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='tagline',
            field=models.CharField(blank=True, default='Knowledge and Virtue', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='GradeRecord',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
