# Generated by Django 6.1.1 on 2026-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_schoolbranding_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='trimester',
            field=models.CharField(default='Trimester 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='accent_color',
            field=models.CharField(default='#eab308', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='banner_announcement',
            field=models.CharField(blank=True, default='Welcome to the official Al-Wasilah Portal!', max_length=500),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='contact_email',
            field=models.EmailField(default='info@alwasilah.edu.gh', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='contact_phone',
            field=models.CharField(default='+233 20 000 0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='logo_text',
            field=models.CharField(default='Al-Wasilah Portal', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#581c87', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='secondary_color',
            field=models.CharField(default='#2e1065', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='website_url',
            field=models.URLField(blank=True, default='https://alwasilah.edu.gh', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+233 20 000 0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
