# Generated by Django 6.1.1 on 2026-09-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_teacherprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolbranding',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='schoolbranding',
            name='secondary_color',
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='primary_color',
            field=models.CharField(default='#800020', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='school_name',
            field=models.CharField(default='Al-Wasilah School Complex', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='tagline',
            field=models.CharField(default='Excellence in Education', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
