# Generated by Django 6.1.1 on 2026-09-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_schoolbranding_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranding',
            name='secondary_color',
            field=models.CharField(default='#1A252C', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='tagline',
            field=models.CharField(default='Knowledge and Virtue', max_length=255),
        ),
    ]
