# Generated by Django 6.1.1 on 2026-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_schoolbranding_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
