# Generated by Django 6.1.1 on 2026-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_userprofile_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranding',
            name='email_address',
            field=models.EmailField(default='info@alwasilah.edu.gh', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolbranding',
            name='phone_number',
            field=models.CharField(default='+233 00 000 0000', max_length=20),
        ),
    ]
