# Generated by Django 6.1.1 on 2026-09-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_schoolbranding_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranding',
            name='address',
            field=models.TextField(default='P.O. Box 123, School Location'),
        ),
        migrations.AddField(
            model_name='schoolbranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_branding/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
